version: "3.2"

services:
    nginx:
        image: nginx:alpine
        network_mode: host
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf

    echo:
        image: caa06d9c/echo
        network_mode: host
        command: --ip 127.0.0.1 --port 8080
